// src/components/user/Barcode.tsx
import Barcode from "react-barcode";
import { useStore } from "@nanostores/react";
import { isEmpty, userInfo } from "../../stores/info";
import { useEffect } from "react";
import Pass from "../../api/Pass";

export default function () {
  const info = useStore(userInfo);

  useEffect(() => {
    if (isEmpty.get()) {
      Pass.Get().then((data) => {
        userInfo.set(data);
      });
    }
  }, []);

  return (
    <>
      {info?.barcode && (
        <Barcode
          value={info.barcode}
          height={48}
          displayValue={false}
          margin={0}
          background="transparent"
        />
      )}
    </>
  );
}

// src/components/user/Barcode.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import JsBarcode from "jsbarcode";
  import Pass from "../../api/Pass";
  import { isEmpty, userInfo } from "../../stores/info";

  function updateBarcode() {
    JsBarcode(barcode, $userInfo.barcode, {
      format: "CODE128",
      lineColor: "#1C232E",
      height: 48,
      displayValue: false,
      margin: 0,
    });
  }

  onMount(() => {
    if (isEmpty.get()) {
      Pass.Get().then((data) => {
        userInfo.set(data);
        updateBarcode();
      });
    } else {
      updateBarcode();
    }
  });

  let barcode: SVGSVGElement;
</script>

<div class="barcode">
  <svg bind:this={barcode} />
  <p>{$userInfo.barcode}</p>
</div>

<style lang="scss">
  .barcode {
    border-radius: 0 0 12px 12px;
    padding: 24px 32px;

    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    background-color: white;

    p {
      color: #1c232e;
      font-size: 15px;
      font-weight: 400;
      line-height: 150%;
    }
  }
</style>
